#服务器端口
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

#运用是激活配置文件{application-{key}.yml or application-{key}.properties}
spring:
  profiles:
    active: test
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    multipart:
      max-file-size: 6mb
      max-request-size: 1024mb


mybatis:
  mapper-locations: classpath:com/tangmo/shengmei/mapper/*.xml

---

spring:
  profiles: test
  datasource:
      url: jdbc:mysql://localhost:3306/shengmei?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&allowMultiQueries=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 1

#mybatis:
#  mapper-locations: classpath:com/mclinical/mapper/*.xml







